version: "3.7"

#ideas taken from https://knplabs.com/en/blog/how-to-dockerise-a-symfony-4-project

services:
  symfony_app:
    build:
      context: ./
      dockerfile: docker/symfony_app/Dockerfile
    container_name: basicrum_bo_php
    env_file:
      - app.env
    volumes:
      - ./beacon_app:/var/www/html:delegated
      - ./docker/symfony_app/www.conf:/usr/local/etc/php-fpm.d/www.conf # local dev only, should not be used for production
    command: # local dev only, should not be used for production
      - "php-fpm"
      - "-R"
    networks:
      - basicrum_bo_network

  crons:
    build:
      context: .
      dockerfile: docker/crons/Dockerfile
    container_name: basicrum_bo_crons
    environment:
      - CLICKHOUSE_HOST=172.17.0.1
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASS=
    volumes:
      - ./beacon_app:/var/www/html:delegated
    depends_on:
      - symfony_app

  nginx:
    image: nginx:1.17-alpine
    container_name: basicrum_bo_nginx
    volumes:
      - ./beacon_app:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8086:80
    depends_on:
      - symfony_app
    networks:
      - basicrum_bo_network

networks:
  basicrum_bo_network:
    driver: bridge
