-
  internal_identifier: simple_tm_connect_duration
  metric_name: ConnectDuration
  field_name: connect_duration
  table_name: rum_data_flat
  return_type: int
  root_type: Simple
  sub_type: Technical
  data_flavors:
    - histogram_first_page_view
    - bounce_rate_in_metric
    - histogram
    - percentile
    - count
-
  internal_identifier: simple_tm_first_contentful_paint
  metric_name: FirstContentfulPaint
  field_name: first_contentful_paint
  table_name: rum_data_flat
  return_type: int
  root_type: Simple
  sub_type: Technical
  data_flavors:
    - histogram_first_page_view
    - bounce_rate_in_metric
    - histogram
    - percentile
    - count
-
  internal_identifier: simple_tm_first_paint
  metric_name: FirstPaint
  field_name: first_paint
  table_name: rum_data_flat
  return_type: int
  root_type: Simple
  sub_type: Technical
  data_flavors:
    - histogram_first_page_view
    - bounce_rate_in_metric
    - histogram
    - percentile
    - count
-
  internal_identifier: simple_tm_load_event_end
  metric_name: LoadEventEnd
  field_name: load_event_end
  table_name: rum_data_flat
  return_type: int
  root_type: Simple
  sub_type: Technical
  data_flavors:
    - histogram_first_page_view
    - bounce_rate_in_metric
    - histogram
    - percentile
    - count
-
  internal_identifier: simple_tm_redirects_count
  metric_name: RedirectsCount
  field_name: redirects_count
  table_name: rum_data_flat
  return_type: int
  root_type: Simple
  sub_type: Technical
  data_flavors:
    - histogram_first_page_view
    - bounce_rate_in_metric
    - histogram
    - percentile
    - count
-
  internal_identifier: simple_tm_time_to_first_byte
  metric_name: TimeToFirstByte
  field_name: first_byte
  table_name: rum_data_flat
  return_type: int
  root_type: Simple
  sub_type: Technical
  data_flavors:
    - histogram_first_page_view
    - bounce_rate_in_metric
    - histogram
    - percentile
    - count
-
  internal_identifier: simple_tm_dns_duration
  metric_name: DnsDuration
  field_name: dns_duration
  table_name: rum_data_flat
  return_type: int
  root_type: Simple
  sub_type: Technical
  data_flavors:
    - histogram_first_page_view
    - bounce_rate_in_metric
    - histogram
    - percentile
    - count
-
  internal_identifier: simple_tm_redirect_duration
  metric_name: RedirectDuration
  field_name: redirect_duration
  table_name: rum_data_flat
  return_type: int
  root_type: Simple
  sub_type: Technical
  data_flavors:
    - histogram_first_page_view
    - bounce_rate_in_metric
    - histogram
    - percentile
    - count
-
  internal_identifier: simple_bm_session_id
  metric_name: SessionId
  field_name: rt_si
  table_name: rum_data_flat
  return_type: string
  root_type: Simple
  sub_type: Business
-
  internal_identifier: simple_bm_user_agent
  metric_name: UserAgent
  field_name: user_agent
  table_name: rum_data_flat
  return_type: string
  root_type: Simple
  sub_type: Business
